language: emacs-lisp
dist: xenial
env:
  - EVM_EMACS=emacs-24.3-travis
  - EVM_EMACS=emacs-24.4-travis
  - EVM_EMACS=emacs-24.5-travis
  - EVM_EMACS=emacs-25.1-travis
  - EVM_EMACS=emacs-25.2-travis
  - EVM_EMACS=emacs-26.1-travis-linux-xenial
  - EVM_EMACS=emacs-26.2-travis-linux-xenial
  - EVM_EMACS=emacs-26.3-travis-linux-xenial
before_install:
  - sudo apt-get install libgnutls30
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > travis.sh && source ./travis.sh
  - evm install "$EVM_EMACS" --use --skip
script:
  - make test
